steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    dir: './appengine-staging'  # or '.' if your app.yaml is in root

availableSecrets:
  secretManager:
    - versionName: projects/urbaneats1/secrets/DB_PASS/versions/latest
      env: 'DB_PASSWORD'
timeout: 900s