serviceAccount: projects/urbaneats1/serviceAccounts/urbaneats1@appspot.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    secretEnv: ['DB_PASSWORD']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo '!**' > .gcloudignore

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    dir: '.'  # or '.' if your app.yaml is in root
    secretEnv: ['DB_PASSWORD']  # Add this if needed by gcloud or App Engine

availableSecrets:
  secretManager:
    - versionName: projects/urbaneats1/secrets/DB_PASS/versions/latest
      env: 'DB_PASSWORD'
timeout: 900s