serviceAccount: projects/urbaneats1/serviceAccounts/urbaneats1@appspot.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: '.'
    secretEnv: ['DB_PASS']

  - name: 'ubuntu'
    entrypoint: 'bash'
    secretEnv: ['DB_PASS']
    args:
      - '-c'
      - |
        echo "env_variables:" > .env.yaml
        echo "  DB_PASS: '${DB_PASS}'" >> .env.yaml
        echo '!**' > .gcloudignore

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet', '--env-vars-file', '.env.yaml']
    dir: '.'

availableSecrets:
  secretManager:
    - versionName: projects/752443826885/secrets/DB_PASS/versions/1
      env: 'DB_PASS'

timeout: 900s
