serviceAccount: projects/urbaneats1/serviceAccounts/urbaneats1@appspot.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: '.'

  - name: 'ubuntu'
    entrypoint: bash
    args:
      - -c
      - |
        cp target/UrbanEats-0.0.1-SNAPSHOT.jar app.jar

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy', 'app.yaml', '--quiet', '--verbosity=debug' ]
    dir: '.'

timeout: 900s
