serviceAccount: projects/urbaneats1/serviceAccounts/urbaneats1@appspot.gserviceaccount.com
options:
  logging: LEGACY
steps:
  - name: 'gcr.io/cloud-builders/busybox'
    entrypoint: 'sh'
    args: [ '-c', 'echo "🔍 Listing files:" && ls -al && cat pom.xml || echo "No pom.xml found"' ]

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    secretEnv: ['DB_PASSWORD']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    dir: './appengine-staging'  # or '.' if your app.yaml is in root
    secretEnv: ['DB_PASSWORD']  # Add this if needed by gcloud or App Engine

availableSecrets:
  secretManager:
    - versionName: projects/urbaneats1/secrets/DB_PASS/versions/latest
      env: 'DB_PASSWORD'
timeout: 900s